// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `ChangePasswordResult`.
export const ChangePasswordResult = __t.enum("ChangePasswordResult", {
  Success: __t.unit(),
  Err: __t.unit(),
});
export type ChangePasswordResult = __Infer<typeof ChangePasswordResult>;

export const Person = __t.object("Person", {
  userid: __t.string(),
  passhash: __t.string(),
});
export type Person = __Infer<typeof Person>;

// The tagged union or sum type for the algebraic type `PublishResult`.
export const PublishResult = __t.enum("PublishResult", {
  Success: __t.unit(),
  Err: __t.unit(),
});
export type PublishResult = __Infer<typeof PublishResult>;

export const Published = __t.object("Published", {
  owner: __t.string(),
  module: __t.string(),
  version: __t.string(),
});
export type Published = __Infer<typeof Published>;

// The tagged union or sum type for the algebraic type `SetResult`.
export const SetResult = __t.enum("SetResult", {
  Success: __t.unit(),
  Err: __t.unit(),
});
export type SetResult = __Infer<typeof SetResult>;

// The tagged union or sum type for the algebraic type `SignupResult`.
export const SignupResult = __t.enum("SignupResult", {
  Success: __t.unit(),
  Err: __t.unit(),
});
export type SignupResult = __Infer<typeof SignupResult>;

export const Storage = __t.object("Storage", {
  ownerKey: __t.string(),
  value: __t.string(),
});
export type Storage = __Infer<typeof Storage>;

